import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="z-[50] hidden lg:flex sticky top-0 w-full bg-[#0a192f] border-b border-white/[0.1]">
          <nav className="border-b border-white/[0.1] lg:max-w-4xl mx-auto">
            navbar
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
